### ISSUE TITLE
Title labels need more information

### ISSUE THREAD

**Issue by Prukutu** [nwrye/CLIM680Project_Assignments#2]
Hi Nik,

Very nice figure overall. The figure itself needs a bit more information for interpretation. For example, what is the time period covered in the mean?

**Comment by nwrye** [comment]
The data is the mean over the late Pliocene. I will update the code to reflect this and would like to request it to be regraded. Thanks!

**Comment by Prukutu** [comment]
You have addressed the issue. Thank you!

**Comment by Prukutu** [comment]
Closing.
